version: 2
updates:
  # - package-ecosystem: "pip"
  #   directory: "/apps/api"
  #   schedule:
  #     interval: "weekly"
  #     day: "wednesday"
  #     time: "09:00"
  #     timezone: "Australia/Perth"
  #   groups:
  #     all-dependencies:
  #       patterns:
  #         - "*"
  #   target-branch: "main"
  #   open-pull-requests-limit: 10
  #   labels:
  #     - "dependencies"
  #     - "python"
  #   ignore:
  #     - dependency-name: "*"
  #       update-types: ["version-update:semver-major"]
  #   commit-message:
  #     prefix: "deps"
  #     include: "scope"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Australia/Perth"
    groups:
      all-dependencies:
        patterns:
          - "*"
    target-branch: "main"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "deps"
      include: "scope"
